name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build YAPFA
      run: |
        git submodule init
        git submodule update --init --recursive
        git config --global user.email "ci@github.com"
        git config --global user.name "Github CI"
        yapfaDir=`pwd`
        cd Tuinity
        ./tuinity jar
        cd $yapfaDir
        ./yapfa patch
        ./yapfa build
