name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build YAPFA
      run: |
        git submodule init
        git submodule update
        git config --global user.email "ci@github.com"
        git config --global user.name "Github CI"
        ./yapfa up
        ./yapfa patch
        ./yapfa build
