name: YAPFA Build Script

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - dev/ver/1.16.1
      - master
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - dev/ver/1.16.1
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 8, 14]

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2.2.0
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1.3.0
      with:
        java-version: ${{ matrix.java }}
    - name: Pull Maven Cache
      uses: actions/cache@v2
      id: maven-cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - uses: s4u/maven-settings-action@v2.1.0
      name: Use ${{ matrix.java }} as the java target
      with:
        properties: '[{"maven.compiler.target": "${{ matrix.java }}"}]'
    - name: Setup YAPFA Project
      run: |
         git submodule update --init --recursive -f
         git config --global user.email "ci@github.com"
         git config --global user.name "Github CI"
         sudo chmod -R -f 777 scripts   
    - name: Build Maven Depends
      if: steps.maven-cache.outputs.cache-hit != 'true'
      run: |
         cd Tuinity
         ./tuinity jar
         cd ..//           
    - name: Build YAPFA
      run: |
        ./yapfa full
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.0.1
      with:
        name: YAPFA-${{ matrix.java }}
        path: target/YAPFA-1.16.1-paperclip.jar
