name: Upstream

on:
  schedule:
  - cron: "*/15 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - name: Update Tuinity
      run: |
        git submodule init
        git submodule update --init --recursive
        git config --global user.email "ci@github.com"
        git config --global user.name "Github CI"
        yapfaDir=`pwd`
        cd Tuinity
        pwd
        git status
        git fetch
        git reset --hard origin/head
        cd ..
        ./patchPaper.sh
        cd Tuinity
        ./tuinity jar
        cd $yapfaDir
        ./yapfa patch
        ./yapfa rb
        ./yapfa patch
        ./yapfa build
        ./yapfa paperclip
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update upstream
          title: '[Automated] Update upstream'
          body: 'Updates Upstream from https://github.com/Spottedleaf/Tuinity'
